# Generated by Django 3.2.8 on 2022-01-27 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior_segment', models.BooleanField(default=None, verbose_name='anterior_segment')),
                ('posterior_segment', models.BooleanField(default=None, verbose_name='posterior_segment')),
                ('long_segment', models.BooleanField(default=None, verbose_name='long_segment')),
                ('fronto_occipital_fasciculus', models.BooleanField(default=None, verbose_name='fronto_occipital_fasciculus')),
                ('inferior_longitudinal_fasciculus', models.BooleanField(default=None, verbose_name='inferior_longitudinal_fasciculus')),
                ('uncinate_fasciculus', models.BooleanField(default=None, verbose_name='uncinate_fasciculus')),
                ('frontal_aslant_tract', models.BooleanField(default=None, verbose_name='frontal_aslant_tract')),
            ],
            options={
                'verbose_name': 'Экземпляр',
                'verbose_name_plural': 'Экземпляры',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transparency', models.JSONField(verbose_name='Прозрачность')),
                ('brightness', models.JSONField(verbose_name='Яркость')),
                ('visibillity', models.JSONField(verbose_name='Видимость')),
                ('instance', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.instance')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки отображения',
                'verbose_name_plural': 'Настройки отображения',
            },
        ),
    ]
